# Generated by Django 4.1.6 on 2023-02-23 08:26

import Scanner.extra
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=Scanner.extra.ContentTypeRestrictedFileField(blank=True, max_length=250, null=True, upload_to='qrcodes/image'),
        ),
    ]
