# Generated by Django 4.1.6 on 2023-02-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0002_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='qrcodes/image'),
        ),
    ]
