# Generated by Django 4.1.6 on 2023-02-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scanner', '0003_alter_person_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='image',
        ),
        migrations.AddField(
            model_name='person',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='qrcodes'),
        ),
    ]
